version: "3"
services:
  api:
    build: api/
    ports:
      - "3000:3000"
  db:
    build: database/
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: dblab

  proxy:
    build: proxy/
    ports:
    - "3001:3001"

