create database dblab;
use dblab;
CREATE TABLE t(id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,create_db TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,path VARCHAR(30) NOT NULL,ua VARCHAR(30) NOT NULL);